version: "3.9"

services:

#  user-info-service:
#    build: ./user-info-service/
#    ports: 
#      - "8000:8000"
  test-application:
    build: ./test-application/
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment: 
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181


# bin/kafka-topics.sh --create --topic test-topic --bootstrap-server localhost:9092
# bin/kafka-topics.sh --describe --topic test-topic --bootstrap-server localhost:9092